- README.md
> Add context stream to readme

- .licenserc.json
> include license in license check

- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
> added terraform CI

- source/Energinet.DataHub.MeteringPoints.Application/Transport/Channel.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/IInboundMessage.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/IOutboundMessage.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/MessageDeserializer.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/MessageDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/MessageExtractor.cs
- source/Energinet.DataHub.MeteringPoints.Application/Transport/MessageSerializer.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Assets/Something.proto
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/Integration/OneOfConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/Integration/ServiceCollectionReceiveProtobuf.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/Integration/ServiceCollectionSendProtobuf.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufInboundMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufInboundMapperFactory.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufInboundMapper`1.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufMessageDeserializer.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufMessageSerializer.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufOutboundMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufOutboundMapperFactory.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufOutboundMapper`1.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufParser.cs
> Introduce transport framework

- .github/utilities/md-spellcheck/wordlist.txt
- .github/workflows/codecov-ci.yml
- README.md
- codecov.yml
Configure codecov.io for metering points repository
> Add code cov to metering points repository

- NOTICE.md
Update the notice file since the codecov GitHub action is not listed
> Update notice with the new usage of a GitHub action

- NOTICE.md
Add missing GitHub action to notice file
> Update notice file with new GH action

- README.md
> Update README with proper background on arch picture.md

- source/Energinet.DataHub.MeteringPoints.Application/Address.cs
- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Application/Energinet.DataHub.MeteringPoints.Application.csproj
- source/Energinet.DataHub.MeteringPoints.Application/UserIdentity/IUserContext.cs
- source/Energinet.DataHub.MeteringPoints.Application/UserIdentity/UserContext.cs
- source/Energinet.DataHub.MeteringPoints.Application/UserIdentity/UserIdentity.cs
- source/Energinet.DataHub.MeteringPoints.Application/UserIdentity/UserIdentityFactory.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.Domain/Energinet.DataHub.MeteringPoints.Domain.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/HttpUserContextMiddleware.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/ServiceBusUserContextMiddleware.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Ingestion/InternalServiceBus.cs
```
<Nullable>enable</Nullable>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
<GenerateDocumentationFile>true</GenerateDocumentationFile>
```
Added to Domain, Application and ApplyDBMigrationsApp projects.
> add missing properties to csproj files

- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
Changed the setup of integrations tests to use simpleinjector.
> use simpleinjector in integration tests

- source/Energinet.DataHub.MeteringPoints.Application/Address.cs
- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/CreateMeteringPointHttpTrigger.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Mappers/CreateMeteringPointMapper.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TransportTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
Changed CreateMeteringPoint class to a record.
> change CreateMeteringPoint to record

- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointSubType.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MeteringPointTests.cs
Add `MeteringPointSubType` to `MeteringPoint`.
> Add metering point subtype

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202105251000 Add outbox index.sql
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Outbox/OutboxManager.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> add nonclustered index

- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> Re-add CleanupDatabase

- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ExchangeMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ProductionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/SampleData.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/SampleData.cs
Change PowerPlant to type of GsrnNumber instead of string.
> Add power plant GSRN number

- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/SettlementMethod.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MeteringPointTests.cs
Add `SettlementMethod` value object to `ConsumptionMeteringPoint`.
> Add settlement method

- .github/actions/meteringpoint-apply-db-migrations/action.yml
- .github/workflows/infrastructure-cd.yml
> Added DbUp executing to Terraform Config

- source/Energinet.DataHub.MeteringPoints.Domain/SeedWork/Internals/EnumerationReflection.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/BusinessRequestProcessing/Pipeline/InputValidationBehavior.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Ingestion/Mappers/CreateMeteringPointMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Contracts/Contract.proto
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Mappers/CreateMeteringPointMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/SystemDateTimeProvider.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TransportTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Application/CreateMeteringPointMapperTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj
What's included:
- Adds better error description when FromName fails.
- Adds missing registrations.
- Adds unit test that ensures mapping between Command and Contract for CreaterMeteringPoint.
- Adds properties to both mappers.
> Various fixes

- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ReadingOccurrence.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/CreateMeteringPoint/Input/CreateMeteringPointXmlDeserializer.cs
Updates XML with a few EDI mappings.
Bonus: fixed type.
> Update XML deserializer

- .github/actions/meteringpoint-apply-db-migrations/action.yml
- .github/workflows/infrastructure-cd.yml
- .github/workflows/infrastructure-ci.yml
- build/infrastructure/evh-meteringpoint.tf
- build/infrastructure/outputs.tf
> Added missing steps to TF CI

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/CreateMeteringPointHttpTrigger.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
Updated the CreateMeteringPoint http endpoint to return 400 Bad request in case the deserializing fails.
* #31
> Xml deserializer update

- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
> use different environment for TF CI

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
Aligned env variables with TF naming.
> Fix env settings naming

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
Added infrastructure assembly to scan for its handlers (I.e. integration event)
> Added infrastructure assembly handlers to configuration

- build/infrastructure/azfun-outbox.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- Fixed DI handlers and missing dependencies
- Fixed TF env variables
> Fix event integration

- .github/workflows/ingestion-cd.yml
- .github/workflows/outbox-cd.yml
- .github/workflows/processing-cd.yml
Remove documentation dispatch, this is a legacy and not open sourced supported way of handling our documentation.
This will be revisited once QA has requirements for what when and where this is needed.
> Remove documentation dispatch

- .github/workflows/infrastructure-cd.yml
> removed unused Python setup in Terraform cd

- .github/workflows/infrastructure-cd.yml
- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
- .github/workflows/license-check-ci.yml
- .github/workflows/md-check.yml
- NOTICE.md
> change checkout actions branch pointer

- .github/actions/configure-terraform-backend/action.yml
The configure-terraform-backend action was accidently removed
> fixed bug introduced in da9b60195069de5134deb1abddbfface20e9660b

- .github/CODEOWNERS
> added erduna to codeowners of business processes

- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
We are working on a better solution to test this.
> Disable Terraform CI until further notice

- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
> re-enable tf ci

- build/infrastructure/stor-postoffice.tf
> fix terraform name length issue

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/ConverterMapperConfigurationBuilder.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/ExtendedPropertyInfo.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/XmlElementInfo.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/XmlMapper.cs
- source/Energinet.DataHub.MeteringPoints.Tests/EDI/CreateMeteringPoint/CreateMeteringPointCimXml.xml
> Added enhancements from Market Roles to XML Converter

- build/infrastructure/azfun-processing.tf
- build/infrastructure/sb-integration-event-shared.tf
TF integration event updates
* #0000
> TF integration event updates

- build/infrastructure/variables.tf
> Variable added TF

- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Tests/EDI/CreateMeteringPoint/XmlConverterTests.cs
> added translator for net settlement group

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringPointSubTypeMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PowerPlantMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/MeteringPointSubTypeValueMustBeValidValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/PowerPlantValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointType.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeteringPointSubTypeValueMustBeValidErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/PowerPlantNotEmptyValidationErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/ErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
Validation Rules:
- The power plant field is mandatory for MPs: D01,
- The power plant field is not allowed for MPs: D20 & D99, D15, D02, E20
- The sub type of a metering point has domain values D01 (Physical), D02 (Virtual), D03 (Calculated)
* #71
> Validation Rules

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/CapacityRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/GsrnNumberMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/StreetCodeMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/CapacityMaximumLengthErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/PostOffice/TempPostOfficeStorageClient.cs
- Pass through original value in xml mapping.
- Add json file extension to temp postoffice, for better debugging experience.
- Remove citation signs in validation error message.
- Fix cascading bug in validations.
> Various minor fixes

- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/SettlementMethodMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/SettlementMethodNotAllowedValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/SettlementMethodRequiredValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Contracts/Contract.proto
Settlement Method changed to nullable type in CreateMeteringPoint, since it´s only mandatory for Consumption and Grid Loss metering points.
* #0000
> Settlement Method changed to nullable type

- source/Energinet.DataHub.MeteringPoints.Application/Common/BusinessProcessResult.cs
- source/Energinet.DataHub.MeteringPoints.Application/ConnectMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringPointMustBeKnownRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/MeteringPointMustBeKnownRuleError.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/MeteringPointMustHavePhysicalStateNewRule.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/MeteringPointMustHavePhysicalStateNewRuleError.cs
- source/Energinet.DataHub.MeteringPoints.Domain/SeedWork/BusinessRulesValidationResult.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeteringPointMustBeKnownRuleErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeteringPointMustHavePhysicalStateNewErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/ConnectMeteringPoints/ConnectTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/SampleData.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/ConnectionRuleTypeTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/DisconnectionRuleTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/LocalDescriptionRuleTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/MeteringPointSubTypeRuleTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/PowerPlantRuleTests.cs
Added business rules to Connect Metering Point to ensure that:
- The Metering Point with the requested GSRN exists
- The metering point must have physical state new
* #0000
> Added business rules for Connect Metering Point

- source/Energinet.DataHub.MeteringPoints.Infrastructure/ContainerExtensions/SimpleInjectorExtensions.cs
- source/ExternalAnnotations/FluentValidation.xml
- source/ExternalAnnotations/MediatR.xml
To make it obvious that implementations that are registered/invoked by Open Generics or Reflection are actually used, i´ve added external annotations to apply UsedImplicitly attributes to implementations of IValidator and IRequestHandler.
* #0000
> External Annotations

- build/infrastructure/main/azfun-internalcommanddispatcher.tf
Add Internal Command Dispatcher to IaC
* #0000
> Add Internal Command Dispatcher to IaC

- .github/actions/terraform-cd/action.yml
- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
> Yaml action Storage updated

- .github/workflows/infrastructure-ci-destroy.yml
- .github/workflows/infrastructure-ci.yml
> Update tf vars in infrastructure CI destroy

- .github/actions/delete-terraform-state/action.yml
- .github/workflows/infrastructure-ci-destroy.yml
> added state handling

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202108171120 Update column data types.sql
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
> Bugfix: Wrong SQL data type for field MeteringGridArea

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
> Add local settings sample in ingestion host

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202108171611 Change columns for connection state.sql
You cannot create a column via ALTER TABLE that is NOT NULL. 
* #0000
> Update Alter Table statement

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.InternalCommandDispatcher/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
> Update local settings samples

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202108191611 Update Production Metering Point Column Data Type.sql
> Update Production MeteringPoint Column

- source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.Application/Queries/MeteringPointGsrnExistsQuery.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringPointGsrnMustBeUniqueRule.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointGsrnExistsQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- The identification of a metering point (GSRN) is unique within GEH (also historically)
- The metering point cannot already exist
* #71
> Added business rule validating GsrnNumber uniqueness

- source/Energinet.DataHub.MeteringPoints.Infrastructure/PostOffice/TempPostOfficeStorageClient.cs
> Changed extension name from .json to .xml in TempPostOffice

- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ExchangeMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointCreated.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ProductionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedEventMessageMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedNotificationHandler.cs
> Add to and from grid to integration event

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/SettlementMethodMustBeValidRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/SettlementMethodMissingRequiredDomainValuesValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/SettlementMethodRequiredValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/Create/SettlementMethodMissingRequiredDomainValuesErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/Create/SettlementMethodRequiredErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
Removed conditional branches from input validation rule since this must be handled as an invariant at domain layer.
> Refactor: Input validation rule for settlement method

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeterReadingOccurenceRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/MeterReadingOccurenceInvalidValueValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/MeterReadingOccurenceMandatoryValidationError.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeterReadingOccurenceInvalidValueErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeterReadingOccurenceMandatoryErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
> Refactor: Input validation rule for meter reading occurrence

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/NetSettlementGroupRule.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> Refactor: Remove conditionals from net settlement group input validation rule

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
> Re-enabled the integration event receiver

- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/EffectiveDate.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/ConnectMeteringPoints/ConnectTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> Fix EffectiveDate mapping bug

- .github/workflows/infrastructure-cd.yml
> added db up path to infrastructureCD

- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeasureUnitTypeRule.cs
- source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeterReadingOccurenceRule.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/ConsumptionMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/CreationRules.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/Rules/InvalidMeterReadingOccurrenceRuleError.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Consumption/Rules/MeteringReadingOccurrenceRule.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MarketMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MarketMeteringPoints/CreationRules.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MarketMeteringPoints/Rules/InvalidMeterReadingOccurrenceRuleError.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MarketMeteringPoints/Rules/MeterReadingOccurrenceRule.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidMeterReadingOccurrenceRuleErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/MarketMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Consumption/CreationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MarketMeteringPoints/CreationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MarketMeteringPoints/MarketMeteringPointMock.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MarketMeteringPoints/MarketMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
> Add meter reading occurrence rule

- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
> Add test for measurement unit type

- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
- source/Energinet.DataHub.MeteringPoints.Tests/EDI/CreateMeteringPoint/CreateMeteringPointCimXml.xml
> Fixed power plant element key

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202108210931 Rename Occurence to EffectiveDate.sql
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202110111554 Rename IsOfficialAddress to IsActualAddress.sql
Reverted Occurence -> EffectiveDate script to its proper state and added the script to the IsOfficialAddress -> IsActuallAddress script instead.
* #0000
> Fixed db script mixup

- .github/workflows/localmessagehub-cd.yml
- .github/workflows/localmessagehub-ci.yml
- build/infrastructure/main/azfun-localmessagehub.tf
> add IaC + CI/CD for localmessagehub

- .github/workflows/infrastructure-cd.yml
> Remove including testdata for db migrations to test environment

- build/infrastructure/main/azfun-outbox.tf
> metering-point-message-dequeued Topic added

- build/infrastructure/main/azfun-localmessagehub.tf
> Add missing connection string

- build/infrastructure/main/azfun-localmessagehub.tf
- build/infrastructure/main/azfun-outbox.tf
- build/infrastructure/main/kv-sharedresources.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/local.settings.sample.json
> Add message hub container name to app settings

- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Energinet.DataHub.MeteringPoints.Client.Abstractions.csproj
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/IMeteringPointClient.cs
- source/Energinet.DataHub.MeteringPoints.Client/Energinet.DataHub.MeteringPoints.Client.csproj
- source/Energinet.DataHub.MeteringPoints.Client/MeteringPointClient.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Client/MeteringPointClientTests.cs
> Add cancellationtoken

- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Energinet.DataHub.MeteringPoints.Client.Abstractions.csproj
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/IMeteringPointClient.cs
- source/Energinet.DataHub.MeteringPoints.Client/Energinet.DataHub.MeteringPoints.Client.csproj
- source/Energinet.DataHub.MeteringPoints.Client/MeteringPointClient.cs
> Add default value for cancellation token

- Directory.Build.props
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Energinet.DataHub.MeteringPoints.Client.Abstractions.csproj
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/IMeteringPointClient.cs
- source/Energinet.DataHub.MeteringPoints.Client/Energinet.DataHub.MeteringPoints.Client.csproj
- source/Energinet.DataHub.MeteringPoints.Client/MeteringPointClient.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Client/MeteringPointClientTests.cs
> Rollback use of cancellationtoken

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/Consumption/ConsumptionMeteringPointCreatedIntegrationEventExtension.cs
Fix casing causing exception in outbox when netsettlement group is set to 99.
> fix casing for nsg 99

- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> Queue name updates

- build/infrastructure/main/app-webapi.tf
> move app service to linux plan

- build/infrastructure/main/app-webapi.tf
> added dotnet version to webapi

- source/Energinet.DataHub.MeteringPoints.Infrastructure/BusinessRequestProcessing/Authorization/AuthorizationRegistrationExtensions.cs
> Register IAuthorizer Create Special Metering Point

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/RequestDefaultChargeLinksDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/ChargesResponseReceiver.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
> Charges package update

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
Updates the Chargelink client package references.
* #0000
> update chargelink client package

- .github/workflows/client-publish.yml
> Add minimal workflow for client package deployment

- README.md
- docs/development.md
- docs/getting-started.md
Updates docs with getting started section.
* #0000
> update docs with getting started

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Functions/MeteringPointHttpTrigger.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.InternalCommandDispatcher/Functions/Dispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.InternalCommandDispatcher/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Functions/OutboxWatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
moves all function entrypoints to `functions` folder.
> Move all function entrypoints to functions folder

- .github/workflows/client-publish.yml
> Re-add workflow for client package deployment

- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
> Fix wrong mapping

- build/infrastructure/main/app-webapi.tf
Add Application Insights to web api.
> add appi to webapi terraform

- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Client/MeteringPointClientTests.cs
Fixes an exception when "searching" for a GSRN that's not found.
> Fix null exception for not found

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/MessageHub/DataAvailableNotificationDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Messaging/Energinet.DataHub.MeteringPoints.Messaging.csproj
- source/Energinet.DataHub.MeteringPoints.Messaging/LocalMessageHubClient.cs
- source/Energinet.DataHub.MeteringPoints.Tests/LocalMessageHub/LocalMessageHubTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/LocalMessageHub/Mocks/PostOfficeMessageMetadataRepositoryMock.cs
- source/Energinet.DataHub.MeteringPoints.Tests/LocalMessageHub/Mocks/StorageHandlerMock.cs
> update messagehub package

- .github/workflows/client-publish.yml
> Update refrence to .github to new version

- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Energinet.DataHub.MeteringPoints.Client.Abstractions.csproj
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Enums/ReadingOccurrence.cs
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Models/MeteringPointCimDto.cs
- source/Energinet.DataHub.MeteringPoints.Client/Energinet.DataHub.MeteringPoints.Client.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
> Add reading occurrence as enum in mp client dto

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- source/Energinet.DataHub.MeteringPoints.Application/Queries/MeteringPointDto.cs
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Energinet.DataHub.MeteringPoints.Client.Abstractions.csproj
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Models/MeteringPointCimDto.cs
- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Models/MeteringPointSimpleCimDto.cs
- source/Energinet.DataHub.MeteringPoints.Client/Energinet.DataHub.MeteringPoints.Client.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Startup.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/BusinessDocumentFactory.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Tooling/WebApi/WebApiHost.cs
- source/Energinet.DataHub.MeteringPoints.Tests/EDI/AccountingPointCharacteristics/AccountingPointCharacteristicsSerializerTests.cs
> Add information about possible parent or child relationships in cim dto

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Common/OutboxMessageDispatcherTelemetryDecorator.cs
> update outbox telemetry decorator

- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Consumption/Rules/ScheduledMeterReadingDateFormatRule.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Consumption/ScheduledMeterReadingDateTests.cs
- Update Scheduled Meter Reading format rule
- Add Test
https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-metering-point/585
> Update Scheduled Meter Reading format rule

- source/Energinet.DataHub.MeteringPoints.Application/Create/SetEnergySupplierHACK.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/MarketRoles/MarketRolesBusinessDocumentFactory.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Generic/GenericNotificationBundleHandler.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Generic/GenericNotificationMessageXmlSerializer.cs
> Bundle generic notification

- .github/workflows/ci.yml
Update to correct domain in CI.Yaml
* #0000
> Update to correct domain in ci.yaml

- .github/CODEOWNERS
- .github/workflows/ci.yml
> Remove comments and MD code owners

- .github/workflows/ci.yml
- build/infrastructure/main/providers.tf
- source/MeteringPoints.EntryPoints.IntegrationTests/TestFiles/Cim/ConnectMeteringPoint.xml
- source/MeteringPoints.EntryPoints.IntegrationTests/TestFiles/Cim/CreateMeteringPointConsumption.xml
> Indention mistake corrected

- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Events/MasterDataWasUpdated.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/UpdateMasterDataTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/TestBase.cs
This PR add logic to `MeteringPoint` to handle update and change of `MasterData`
> Master data can be changed

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Seed/202201131240 More Actor seed data.sql
Created a bunch of new actors for our seed data to make it easier to test our system without everyone using the same id and stepping on each others toes.
> More Actors in our seed data

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedIntegrationEventExtension.cs
- Updated "unknown" value for Proto enum to "null"
- Reverted change to non-nullable properties
* #752
> Updated nullable value and properties for proto contract

- .github/CODEOWNERS
> Add Chris as Code Owner

- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataFieldSelector.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ProductionObligationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/AnalysisValidationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/ConsumptionBuilderTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/ExchangeMeteringPointValidationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/ExchangeReactiveEnergyValidationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/InternalUseValidationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/ProductionBuilderTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/SpecialMeteringPointValidationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MasterDataHandling/VEProductionMeteringPointValidationTests.cs
Add rules for production obligation
> Add rules for production obligation

- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataUpdater.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidSettlementMethodErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/SettlementMethodIsRequiredErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/SettlementMethodTests.cs
Reject if settlement method is invalid
* #551
> Reject if settlement method is invalid

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Seed/202201201330 Add grid access provider test data continued.sql
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
Add missing links from last seed data addition.
> add missing links

- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidProductTypeErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidProductTypeValueErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ProductTypeTests.cs
Reject if product type value and configuration is invalid
* #551
> Reject if product type value and configuration is invalid

- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidUnitTypeValueErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeasureUnitTypeIsRequiredErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/UnitTypeTests.cs
Reject if unit type is not valid
* #551
> Reject if unit type is not valid

- source/Energinet.DataHub.MeteringPoints.Application/Create/Validation/RuleSet.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidMeterReadingOccurrenceRuleErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/InvalidReadingPeriodicityTypeErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/MeterReadingPeriodicityIsRequiredErrorConverter.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/MarketMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ProductionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/EffectiveDateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/MeterReadingPeriodicityTests.cs
Reject if meter reading periodicity is not valid
* #551
> Reject if meter reading periodicity is not valid

- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Startup.cs
> Fix startup bug

- source/Energinet.DataHub.MeteringPoints.Domain/Actors/Role.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointByIdQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/Queries/MeteringPointDtoQueryHelper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/ActorMessageService.cs
> Fix query and friends

- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/MeteringPoints/Queries/MeteringPointByGsrnQueryHandler.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/UserProvider.cs
> Securing metering point endpoint

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Functions/MeteringPointHttpTrigger.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointHttpTriggerTests.cs
Changes 200 ok to 202 accepted for ingestion.
> change 200 ok to 202 accepted

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
Adds the missing registration for CreateDefaultChargeLinksNotificationHandler
> add missing chargelinknotificationhandler

- source/Energinet.DataHub.MeteringPoints.Application/Create/SetEnergySupplierHACK.cs
- source/Energinet.DataHub.MeteringPoints.Application/EDI/IActorMessageService.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/ActorMessageService.cs
Allow dynamic role in generic notification. Also set to DDM for the current use (SetEnergySupplierHACK)
> Update RSM-004 with role DDM

- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/AuthorizationConfiguration.cs
> Fix  E2E test

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202203011200 Clean QueuedInternalCommands.sql
Clean QueuedInternalCommands
* #0000
> Clean QueuedInternalCommands

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
Attempt at fixing this exception:
> Updated function worker SDK

- README.md
> Updated read.me with roadmap and context stream

- source/Energinet.DataHub.MeteringPoints.Application/Common/BusinessProcessCommandFactory.cs
- source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPointHandler.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202203011400 Add Administrator to meteringpoints.sql
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterData.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataBuilder.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataBuilderBase.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataUpdater.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Rules/ActorDoesNotExistRuleError.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/SampleData.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Consumption/CreationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Exchange/CreationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/ParentChildTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/Production/CreationTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/SetEnergySupplierTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/UpdateMasterDataTests.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Domain/TestBase.cs
- source/Energinet.DataHub.MeteringPoints.Tests/SampleData.cs
Added ActorId to metering point as "Administrator" upon create
Added "Administrator" field to "Meteringpoints"
Added test for known/unknown actor to ensure only known actors can create
#565
> Add mp admin on create

- source/Energinet.DataHub.MeteringPoints.Application/CloseDown/CloseDownMeteringPoint.cs
- source/Energinet.DataHub.MeteringPoints.Application/Common/Commands/InternalCommand.cs
- source/Energinet.DataHub.MeteringPoints.Application/Connect/AddEnergySupplier.cs
- source/Energinet.DataHub.MeteringPoints.Application/Connect/SendAccountingPointCharacteristicsMessage.cs
- source/Energinet.DataHub.MeteringPoints.Application/Connect/SetEnergySupplierInfo.cs
- source/Energinet.DataHub.MeteringPoints.Application/Integrations/ChargeLinks/Create/CreateDefaultChargeLinks.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/BusinessRequestProcessing/Pipeline/UnitOfWorkBehavior.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/InternalCommands/CommandExecutor.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/InternalCommands/InternalCommandProcessor.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Infrastructure/InternalCommands/InternalCommandProcessorTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
Delegate internal command execution to service to ensure transaction and DI scope isolation
> Delegate internal command execution to service to ensure scope isolation

- README.md
> New try. Update context stream and architecture

- source/Energinet.DataHub.MeteringPoints.Infrastructure/InternalCommands/InternalCommandProcessor.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Infrastructure/InternalCommands/InternalCommandProcessorTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Infrastructure/InternalCommands/TestCommand.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Infrastructure/InternalCommands/TestCommandHandler.cs
- source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj
Add exception handling internal command processing
> Add exception handling internal command processing

- source/Energinet.DataHub.MeteringPoints.Application/Energinet.DataHub.MeteringPoints.Application.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj
Upgraded NuGet packages to add support for custom XML namespace prefixes
Energinet.DataHub.Core.SchemaValidation 1.0.8 -> 1.0.9
Energinet.DataHub.Core.XmlConversion.XmlConverter 1.0.4 -> 1.0.5
Energinet.DataHub.Core.XmlConversion.XmlConverter.Abstractions 1.0.4 -> 1.0.5
Energinet.DataHub.Core.XmlConversion.XmlConverter.SimpleInjector 1.0.4 -> 1.0.5
> Upgraded nuget packages to add suppoort for custom XML namespace

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
Update logging version
* #0000
> Update logging version

- docs/xml-requests/RequestChangeAccountingPointCharacteristics (CloseDown).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics (Connect).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics (Disconnect).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics (Reconnect).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics (Update).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics(Create child).xml
- docs/xml-requests/RequestChangeAccountingPointCharacteristics(CreateMP).xml
> Xml req docs updated

- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/appsettings.json
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/AccountingPointCharacteristics/AccountingPointCharacteristicsMessageXmlSerializer.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Confirm/ConfirmMessageXmlSerializer.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Generic/GenericNotificationMessageXmlSerializer.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Reject/RejectMessageXmlSerializer.cs
Sending xml namespace and schema location was breaking schema validation for market participants. Namespace and schema location has been removed from outgoing messages.
> Remove namespace and schema location

- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/GenericNotification/GenericNotificationMessageFactory.cs
Update BusinessSectorType from E23 to 23 in generic message
* #0000
> Update BusinessSectorType from E23 to 23

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
logging middleware upgrade to 1.2.0
* #0000
> logging middleware upgrade

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
Removed a bunch of lines that don't do anything.
> Cleanup of DB Migration project file

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
> Change NumberOfDaysEffectiveDateIsAllowedToBeforeToday to 720

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
> Change NumberOfDaysEffectiveDateIsAllowedToBeforeToday to 721

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
request response logging upgrade 1.2.1
* #0000
> logging upgrade

- source/Energinet.DataHub.MeteringPoints.Messaging/Bundling/Generic/GenericNotificationMessageXmlSerializer.cs
> Change to generic notification xml to correct order

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj
Updated Core Schemas package to latest version to include latest additions to schema definitions
> Update Schemas NuGet package to version 1.0.10

- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/MasterDataBuilder.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
Issue: https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/internal-repo/175
> Update Create test on capacity

- source/Energinet.DataHub.MeteringPoints.Client.Abstractions/Enums/AssetType.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Components/AssetType.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Consumption/ConsumptionValidator.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Consumption/Rules/AssetTypeNoTechnologyRule.cs
- source/Energinet.DataHub.MeteringPoints.Domain/MasterDataHandling/Rules/AssetTypeNoTechnologyError.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/AssetTypeTests.cs
Implement new asset type D98 
* #0000
> Implement new asset type D98

- .github/actions/publish-release-contents/action.yml
> Add correct folder to publish action

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/MeteringPointDbService.cs
> Update sql with stringbuilders

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/MeteringPointDbService.cs
> Update roles in actorsync

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufMessageParserMap.cs
> Update parser mapper

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.sln
Remove reference to nuget project and only use nuget package 
* #0000
> Remove project references

- .github/workflows/cd.yml
- .github/workflows/client-publish.yml
- .github/workflows/integration-events-publish.yml
- .github/workflows/request-response-publish.yml
- .github/workflows/sonarcloud.yml
> Bump versions i pipeline

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202206231201 Consolidated models.sql
Updated scripts to use create table statements from SQL Server Management Studio instead of Rider.
Seems like Rider doesn't include all the details when exporting a create statement.
> Updated create statements

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/EventMetadata.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/MasterDataRequestListener.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/MasterDataRequestMetadata.cs
> Extract and reply with businessprocessId in meta

- .github/CODEOWNERS
> Remove Dach as code owner

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Changed reference to dotnet-solution-ci.yml temporarily to solve issue with integration test in pipeline
> Changed reference to dotnet-solution-ci

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Functions/MeteringPointHttpTrigger.cs
- source/Energinet.DataHub.MeteringPoints.Messaging/LocalMessageHubDataAvailableClient.cs
Added correlation ID to log when dispatching internal commands and sending dataavailable notification to postoffice
> Add correlation Id to log output

- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/sb-meteringpoint.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Monitor/HealthCheckEndpoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Configuration/HealthCheckRegistration.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Channel.cs
> Health check added processing

- build/infrastructure/main/func-outbox.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Monitor/HealthCheckEndpoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> Add healthcheck outbox

- build/infrastructure/main/func-localmessagehub.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Monitor/HealthCheckEndpoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/local.settings.sample.json
> Add Health check local messagehub

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Monitor/HealthCheckEndpoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
> Health check ingestion added

- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
> Revert queues and topics

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Monitor/HealthCheckEndpoint.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
> Health check actor sync

- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
> Add queues for localmessagehub again

- build/infrastructure/main/func-ingestion.tf
- build/infrastructure/main/func-localmessagehub.tf
- build/infrastructure/main/func-outbox.tf
- build/infrastructure/main/func-processing.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/QueueSubscriber.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.Tests/AzureFunctionHostConfigurationTests.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/IngestionFunctionAppFixture.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/MeteringPointFunctionAppFixture.cs
> Rename queue topic setting

- build/infrastructure/main/func-ingestion.tf
- build/infrastructure/main/func-localmessagehub.tf
- build/infrastructure/main/func-outbox.tf
- build/infrastructure/main/func-processing.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/QueueSubscriber.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.Tests/AzureFunctionHostConfigurationTests.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/IngestionFunctionAppFixture.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/MeteringPointFunctionAppFixture.cs
Give a more descriptive name to the connection string with its permissions for the domain service bus
* #0000
> Upd metering point sb connection string name

- build/infrastructure/main/func-ingestion.tf
- build/infrastructure/main/func-localmessagehub.tf
- build/infrastructure/main/func-outbox.tf
- build/infrastructure/main/func-processing.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/ChargesResponseReceiver.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/IntegrationEventReceiver.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/MasterDataRequestListener.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/QueueSubscriber.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.Tests/AzureFunctionHostConfigurationTests.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/IngestionFunctionAppFixture.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/MeteringPointFunctionAppFixture.cs
> Settings and settings naming cleanup

- build/infrastructure/main/func-ingestion.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/local.settings.sample.json
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> Extend health checks with missing queues checks

- build/infrastructure/main/alerts.tf
> Internal Command message errors alert

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Configuration/HealthCheckRegistration.cs
> Add guid to servicebus queue name

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
Removed duplicate package reference in infrastructure
* #0000
> Add Create charge link Service Bus queue to health check

- build/infrastructure/main/alerts.tf
> Add actorsync to alert

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/CorrelationIdMiddleware.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Correlation/CorrelationContext.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Correlation/ICorrelationContext.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/MessageHubDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Outbox/OutboxMessageFactory.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs
- source/MeteringPoints.EntryPoints.IntegrationTests/MeteringPoints.EntryPoints.IntegrationTests.csproj
> Return correlation id only

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/CorrelationIdMiddleware.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/FunctionExtensions.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/UserProperties.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Program.cs
Refactor correlation id middleware
> Refactor correlation id middleware

- source/Energinet.DataHub.MeteringPoints.Infrastructure/Correlation/CorrelationContext.cs
> Return new correlation id

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
This PR updates `Energinet.Datahub.Charges.Clients.Registration` to latest version `3.0.10`.
* #0000
> Bump: Upgrade `Energinet.DataHub.Charges.Clients.Registration` to `3.0.10`

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Energinet.DataHub.MeteringPoints.ActorRegistrySync.csproj
- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/ActorRegistryDBService.cs
- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/MeteringPointDbService.cs
> Upgrade SQL client package

- source/RequestResponse/documents/release-notes/release-notes.md
- source/RequestResponse/source/RequestResponse/RequestResponse.csproj
- source/RequestResponse/source/RequestResponse/Requests/MasterData/MeteringPointMasterDataRequest.proto
- source/RequestResponse/source/RequestResponse/Requests/MasterData/MeteringPointMasterDataResponse.proto
Restructure master data request contracts
> Restructure master data request contracts

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/ActorRegistryDBService.cs
Changed SQL query for selecting from Actor table to use correct field name.
* #0000
> Changed SQL query for getting actor

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Entities/ActorRegistryActor.cs
- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/MeteringPointDbService.cs
Changed data type on IdentificationType in ActorRegistryActor to string to match Actor table definition.
> Changed data type on IdentificationType in ActorRegistryActor

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/ActorRegistryDBService.cs
Changed order on select statement to match order of fields in record definition
> Changed order on select for GridArea

- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/sbs-market-participant-changed.tf
> Reduced length in names in TF

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/MeteringPointDbService.cs
> Add null check

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/ActorRegistryDBService.cs
Fix grid area and grid area link queries
> Fix grid area and grid area link queries

- build/infrastructure/main/sbs-market-participant-changed.tf
> Update subscription names

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Services/ActorRegistryDBService.cs
> Fix grid area query

- build/infrastructure/main/func-processing.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Configuration/HealthCheckRegistration.cs
> Extend health checks for subscriptions

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Scripts/Model/202209200958 Add index on QueuedInternalCommands.sql
Create index on queued internal commands table
> Create index on queued internal commands table

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/CreateMeteringPointDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/IIntegrationEventTopicSender.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/IntegrationEventDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/IntegrationEventTopicSender.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MasterDataUpdatedDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MeteringPointConnectedDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MeteringPointDisconnectedDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MeteringPointMessageDequeuedIntegrationEventDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/IntegrationEventDispatchers/MeteringPointReconnectedDispatcher.cs
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
> Add extra message against new topic  if needed for integration events

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
> Register event listener

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedEventMessage.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedEventMessageMapper.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedIntegrationEventExtension.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedNotificationHandler.cs
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Transport/Protobuf/ProtobufMessageParserMap.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ExchangeMeteringPointTests.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ProductionMeteringPointTests.cs
> Set grid operator id for event

- build/infrastructure/main/func-processing.tf
- build/infrastructure/main/sbs-integration-events.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/EventListeners/MeteringPointMessageDequeuedListener.cs
> Add mp message dequeeud listener

- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
> register listener

- build/infrastructure/main/mssqldb-this.tf
> db name to kv

- build/infrastructure/main/func-processing.tf
- source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
> Remove old IE queue settings

- .github/CODEOWNERS
> Add patrick as owner

- build/infrastructure/main/mssqldb-this.tf
> Remove db name from kvs

- .github/workflows/cd.yml
> merge workflows introduced in pr #975

- source/Energinet.DataHub.MeteringPoints.Application/Energinet.DataHub.MeteringPoints.Application.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi.csproj
- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Startup.cs
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
> Add Healthcheck web api

- source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi.csproj
> Upgrade core.app.webapp.simpleinjector package

- source/Energinet.DataHub.MeteringPoints.ActorRegistrySync/Energinet.DataHub.MeteringPoints.ActorRegistrySync.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
- source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
> Upgrade SQL client packages

- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Helpers/CustomScriptProvider.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Helpers/DefaultUpgrader.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Helpers/ResultReporter.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Helpers/SqlAppAuthenticationProvider.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Helpers/UpgradeFactory.cs
- source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Program.cs
Ref: https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/662
> Replace DbUp with DbUp.Reboot
