Energinet-DataHub/geh-metering-point

Directory.Build.props

Updates the nuget packages to newest version.
For StyleCop.Analyzers we move to prerelease to get C# 9.0 support.

Update analyzer nuget references

---

source/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp/Energinet.DataHub.MeteringPoints.ApplyDBMigrationsApp.csproj
source/Energinet.DataHub.MeteringPoints.Benchmarks/Energinet.DataHub.MeteringPoints.Benchmarks.csproj
source/Energinet.DataHub.MeteringPoints.Domain/Energinet.DataHub.MeteringPoints.Domain.csproj
source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/Energinet.DataHub.MeteringPoints.EntryPoints.Common.csproj
source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion.csproj
source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox.csproj
source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Energinet.DataHub.MeteringPoints.EntryPoints.Processing.csproj
source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
source/Energinet.DataHub.MeteringPoints.IntegrationTests/Energinet.DataHub.MeteringPoints.IntegrationTests.csproj
source/Energinet.DataHub.MeteringPoints.Tests/Energinet.DataHub.MeteringPoints.Tests.csproj

Set lang version to 9.0 on all projects to avoid build errors (I.e. <Nullable>enable</Nullable> not working)
I was getting errors on my machine like this one. The fix was to specify the C# lang version in all csproj files.

Set C# lang version explicitly to 9.0

---

.github/workflows/codecov-ci.yml

Codecov needs a coverage report created on the default target branch.
In our case this is the main branch.
This PR ensures that the CodeCov-CI is run when a PR is completed or a push to main occurs.

Include CI action when merged on main to create base report for codecov

---

source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointCreated.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointId.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPointType.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/PhysicalState.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MeteringPointTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/SampleData.cs

This PR enriches the `MeteringPoint` model with the following:
- `MeteringPointId`
- `GsrnNumber`
- `PhysicalStatus`
- `MeteringPointType`
- `MeteringPointCreated` domain event
Primitives for the remaining properties have also been added order to enable EF core integration, but these will soon be replaced with proper value objects.

Enrich metering point with attributes

---

source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ExchangeMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ProductionMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs

This PR changes `MeteringPoint` public properties to private fields.
The domain model is write-model, and thus, only the model itself need to know about the internals.

Change public properties to private fields to encapsulate internals

---

source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
source/Energinet.DataHub.MeteringPoints.Domain/Energinet.DataHub.MeteringPoints.Domain.csproj
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Address.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ExchangeMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ProductionMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs
source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/MeteringPointTests.cs

Adds `Address` value object to `MeteringPoint`.
In order to get EF core working, it has been necessary to add private parameterless ctors to metering point objects. However, since EF core is capable of using contructors with parameteres, we should research on this to see if we can get rid of these constructors.

Add address

---

source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/CreateMeteringPoint/CreateMeteringPointRejected.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidDomainErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/GsrnNumberMustBeValidErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Tests/ErrorValidationRegistrationTests.cs

Make status appear as second property in reject message to conform to standard layout

---

source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/CreateMeteringPointRuleSet.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/AddressMustBeValidRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/FloorIdentificationRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/NetSettlementGroupRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/RoomIdentificationRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/StreetCodeMustBeValidRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/FloorIdentificationValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/NetSettlementGroupInvalidValueValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/NetSettlementGroupMandatoryValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/NetSettlementGroupNotAllowedValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/RoomIdentificationValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/StreetCodeValidationError.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/FloorIdentificationErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/NetSettlementGroupInvalidValueErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/NetSettlementGroupMandatoryErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/NetSettlementGroupNotAllowedErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/RoomIdentificationErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/StreetCodeErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/Ingestion/Mappers/CreateMeteringPointMapper.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Contracts/Contract.proto
source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Mappers/CreateMeteringPointMapper.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/ConnectMeteringPoints/ConnectTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/SampleData.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs

Added following Input Validations:
- The street code of a metering point consists of exactly 4 digits in the range 0001 to 9999
- The floor identification of a metering point consists of maximal 4 characters
- The room identification of a metering point consists of maximal 4 characters
- The net settlement group of a metering point is mandatory for Consumption and Production MPs, otherwise not allowed
- The net settlement group of a metering point has domain values 0, 1, 2, 3, 6, and 99
Missing correct codes in Error Converters.
* #0000

Added input validations

---

source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/CreateMeteringPointRuleSet.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/CapacityRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/CapacityIsMandatoryValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/CapacityIsNotAllowedValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/CapacityMaximumLengthValidationError.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/CapacityIsMandatoryErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/CapacityIsNotAllowedErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/CapacityMaximumLengthErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/ConverterMapperConfigurationBuilder.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/Energinet.DataHub.MeteringPoints.Infrastructure.csproj
source/Energinet.DataHub.MeteringPoints.Infrastructure/Ingestion/Mappers/CreateMeteringPointMapper.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Contracts/Contract.proto
source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Mappers/CreateMeteringPointMapper.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/ConnectMeteringPoints/ConnectTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/CapacityRuleTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/RuleSetTest.cs

- The capacity of a metering point consists of maximal 8 characters. Only digits and an optional decimal point are allowed. (only . allowed) (physical)
- The capacity of Production metering points is mandatory (physical)
- The capacity of consumption metering points is mandatory if net settlement group is not 0, else optional (physical)
- The capacity field is not allowed for MP Types: E20, D02, D15, D20, D99 (physical)
Also, introduce separate test files for rule sets.

Add validations for capacity

---

source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringPointSubTypeMustBeValidRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/PowerPlantMustBeValidRule.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs

- If a Consumption metering point (E17) is not in net settlement group 0 or 99 then a power plant is required.
- Meteringpoints of type D08, D09, D10, D11 and D12 must be Virtual (D02) or Calculated (D03).
- If a Consumption (E17) or Production (E18) metering point is not in net settlement group 0 or 99 then sub type must be Virtual (D02) or Calculated (D03).
* #71

Power plant and sub type rules

---

source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/MeteringGridAreaValidRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/SourceMeteringGridAreaNotAllowedValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/TargetMeteringGridAreaNotAllowedValidationError.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/SourceMeteringGridAreaNotAllowedErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/TargetMeteringGridAreaNotAllowedErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/CreateMeteringPointRuleSetTests.cs

- It is not allowed to provide the source metering grid area if a metering point of type is Exchange - Reactive energy (D20).
- It is not allowed to provide the target metering grid area if a metering point of type is Exchange - Reactive energy (D20).
* #0000

Added input validations for source and target metering grid area

---

source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Application/CreateMeteringPointHandler.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/CreateMeteringPointRuleSet.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/Rules/AssetTypeRule.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/AssetTypeMandatoryValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/AssetTypeNotAllowedValidationError.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/AssetTypeWrongValueValidationError.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ConsumptionMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/AssetTypeMandatoryErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/AssetTypeNotAllowedErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/AssetTypeWrongValueErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/ConverterMapperConfigurationBuilder.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/Mappings/CreateMeteringPointXmlMappingConfiguration.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/Processing/Contracts/Contract.proto
source/Energinet.DataHub.MeteringPoints.Tests/Validation/AssetTypeRuleTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Validation/RuleSetTest.cs

- The AssetType has domain values D01 –D20 or D99
- For Production metering point (E18) the AssetType is mandatory. For a Consumption metering point (E17) in net settlement group not 0 the AssetType is mandatory, optional for other net settlement groups. AssetType is optional for TypeOfMP D01, D04 – D12, D17 and D18, else not allowed
* #0000

Asset Type validations

---

source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/XmlConverter/XmlMapper.cs

XmlConverter should return null if parent element for optional field is missing
* #248

XmlConverter optimization

---

source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/Tooling/DatabaseFixture.cs

This PR fixes a bug where a container will be used regardless of whether or not you're running with a local database.
Use IntegrationTests_ConnectionString as local database name.

fix: using local db shouldn't use container

---

source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategies/CacheAllReflectionStrategy.cs
source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategies/CheckOnInvocationReflectionStrategy.cs
source/Energinet.DataHub.MeteringPoints.Benchmarks/ReflectionStrategyBenchmarks.cs
source/Energinet.DataHub.MeteringPoints.Domain/SeedWork/Internals/DictionaryCacheReflectionStrategy.cs
source/Energinet.DataHub.MeteringPoints.Domain/SeedWork/Internals/EnumerationReflection.cs
source/Energinet.DataHub.MeteringPoints.Domain/SeedWork/Internals/ReflectionStrategy.cs
source/Energinet.DataHub.MeteringPoints.Tests/EnumerationTypeTest/ReflectionStrategyTests.cs

Add two new methods to ReflectionStrategy.
- ContainsName
- ContainsValue
They can be used to test if name or value is present within an EnumerationType
|                              Method |    Categories |      Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------------ |-------------- |----------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
| CheckOnInvocationReflectionStrategy |        GetAll | 146.81 ns | 1.683 ns | 1.492 ns |  1.00 |    0.00 | 0.0534 |     - |     - |     168 B |
|          CacheAllReflectionStrategy |        GetAll |  12.94 ns | 0.172 ns | 0.161 ns |  0.09 |    0.00 |      - |     - |     - |         - |
|   DictionaryCacheReflectionStrategy |        GetAll |  29.42 ns …

Add contains to reflection strategy

---

build/infrastructure/main/azfun-internalcommanddispatcher.tf

Sender connection string instead of listener in internal command dispatcher

---

.github/actions/publish-release-contents/action.yml

fix publish-release-action to be compatible with 1.13.0

---

source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/ChargesResponseReceiver.cs

After having tested the creation of default charge links, I would like for small QOL feature. 
This PR will add:
- update to the message being logged when `ChargesResponseReceiver` handles a successful message.
* #0000

updated creation of def links succesfull scenario with a better message

---

source/Energinet.DataHub.MeteringPoints.Application/Create/SetEnergySupplierHACK.cs

…int is created. This is done in order to support the upcoming test
Add hack for setting energy supplier details as when an Accounting point is created. This is done in order to support the upcoming test

Add hack for setting energy supplier details

---

source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/Create/Consumption/InvalidScheduledMeterReadingDateNetSettlementGroupRuleErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/ScheduledMeterReadingDateIsRequiredErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ConsumptionMeteringPointTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ConsumptionMeteringPoints/ChangeTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ScheduledMeterReadingDateTests.cs

Cannot remove scheduled meter reading date if field is required
* #551

Cannot remove scheduled meter reading date if field is required

---

source/Energinet.DataHub.MeteringPoints.Application/ChangeMasterData/ChangeMasterDataHandler.cs
source/Energinet.DataHub.MeteringPoints.Application/ChangeMasterData/ChangeMasterDataRequestValidator.cs
source/Energinet.DataHub.MeteringPoints.Application/Common/ChildMeteringPoints/ParentChildCoupling.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/Events/DecoupledFromParent.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/MeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ParentChild/ChildMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/AssertPersistedMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ParentChildCouplingTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/ParentChildTests.cs

Child metering point can be decoupled from parent via update master data business process
* #551

Child metering point can be decoupled from parent via update master data business process

---

source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ParentChild/ChildMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ParentChild/Rules/CannotCoupleToClosedDownParent.cs
source/Energinet.DataHub.MeteringPoints.Domain/MeteringPoints/ParentChild/Rules/CannotCoupleToClosedDownParentRule.cs
source/Energinet.DataHub.MeteringPoints.Infrastructure/EDI/Errors/Converters/ParentChild/CannotCoupleToClosedDownParentErrorConverter.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/ParentChildTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/UpdateMasterData/ParentChildCouplingTests.cs
source/Energinet.DataHub.MeteringPoints.Tests/Domain/MeteringPoints/ParentChildTests.cs

Cannot couple child to a closed down parent metering point
* #551

Cannot couple child to a closed down parent metering point

---

source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/IntegrationEvents/CreateMeteringPoint/MeteringPointCreatedNotificationHandler.cs

During a test in the Charges domain, it was discovered that the persisted effective date in the Charges domain didn't match effective date in the Metering Point domain.
This PR fixes the problem, by using `EffectiveDate` instead of `OccurredOn` when creating `MeteringPointCreatedEventMessage`.
Metering Point domain:
Charges domain:
* #0000

Fix: `MeteringPointCreatedEventMessage` incorrectly used `OccurredOn` instead of `EffectiveDate`

---

source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/MediatR/MediatorBuilder.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Common/MediatR/SimpleInjectorMediatorContainerExtensions.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.LocalMessageHub/Program.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Outbox/Program.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.WebApi/Startup.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
source/Energinet.DataHub.MeteringPoints.Tests/LocalMessageHub/BundleCreatorTests.cs
source/MeteringPoints.EntryPoints.IntegrationTests/MeteringPoints.EntryPoints.IntegrationTests.csproj

This PR removes the use of assembly scanning for configuring MediatR in the composition root.

Refactor composition roots away from handler assembly scanning

---

source/Energinet.DataHub.MeteringPoints.IntegrationTests/DisconnectMeteringPoints/DisconnectTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/ReconnectMeteringPoints/ReconnectTests.cs

When the connection status of a metering point goes from connected to disconnected an RSM-022 business reason code E79 is sent to the balance supplier
When the connection status of a metering point goes from disconnected to connected an RSM-022 with business reason code E79 is sent to the balance supplier
https://app.zenhub.com/workspaces/batman-60a6105157304f00119be86e/issues/energinet-datahub/geh-metering-point/741

Inform Balance Supplier about change in connection status (Test updates)

---

build/infrastructure/main/func-processing.tf
source/Energinet.DataHub.MeteringPoints.Application/Common/SystemTime/TimeHasPassed.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Functions/SystemTimer.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/Program.cs
source/Energinet.DataHub.MeteringPoints.EntryPoints.Processing/local.settings.sample.json
source/Energinet.DataHub.MeteringPoints.Infrastructure/InternalCommands/ProcessInternalCommandsOnTimeHasPassed.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CloseDown/RequestCloseDownTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/TestHost.cs
source/MeteringPoints.EntryPoints.IntegrationTests/Fixtures/MeteringPointFunctionAppFixture.cs
source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs

This PR adds a AZ function timer trigger to act as system timer, by emitting a `TimeHasPassed` event on scheduled basis. Interested services can subscribe to this event to trigger their on handling logic.
Therefore, the `ProcessInternalCommands` AZ function has been removed, and a notification handler has been added instead.
This decouples scheduled commands from the timer infrastructure, which improves the testability of business processes, since timer events can be emitted deterministically during test.
We will expand this concept later on, to remove the need for scheduled commands entirely.

Add system timer function

---

source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Functions/MeteringPointHttpTrigger.cs
source/MeteringPoints.EntryPoints.IntegrationTests/Functions/MeteringPointFunctionAppTests.cs

Moved correlation id to the header as per our documentation.
Also made sure that we include it on all requests and not just the successful ones.
* https://github.com/Energinet-DataHub/green-energy-hub/issues/270

Moved correlation id to the header instead of body

---

source/Energinet.DataHub.MeteringPoints.Application/Create/Validation/RuleSet.cs
source/Energinet.DataHub.MeteringPoints.Application/Validation/ValidationErrors/CountryCodeMandatoryValidationError.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/CreateTests.cs

Country code was throwing an exception if the field was empty. Turns out it was missing a custom state value.
Added the state and a test.
* https://github.com/Energinet-DataHub/Internal-Repo/issues/165

Fix for country code rule

---

source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Application/Create/Validation/RuleSet.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs

When validating disconnection type it should only be done for consumption, production and exchange meteringpoints 
* #0000

Disconnect should not be validated on child mps

---

source/Energinet.DataHub.MeteringPoints.Application/Create/CreateMeteringPoint.cs
source/Energinet.DataHub.MeteringPoints.Application/Create/Validation/RuleSet.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/CreateMeteringPoints/SpecialMeteringPointTests.cs
source/Energinet.DataHub.MeteringPoints.IntegrationTests/Scenarios.cs

This reverts commit e6006928. The current solution leaks domain logic (and doesn't seem to work as expected).
* https://github.com/Energinet-DataHub/Internal-Repo/issues/167

Revert "Disconnect should not be validated on child mps"

---

source/Energinet.DataHub.MeteringPoints.EntryPoints.Ingestion/Functions/MeteringPointHttpTrigger.cs
source/Energinet.DataHub.MeteringPoints.Messaging/LocalMessageHubDataAvailableClient.cs
source/Energinet.DataHub.MeteringPoints.Tests/LocalMessageHub/LocalMessageHubTests.cs

Added logging on:
- Request received
- Request forwarded to internal processing
- DataAvailableNotification to post office
To be used by SRE team for monitoring

Added logging for SRE team

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/integration-events-publish.yml
.github/workflows/request-response-publish.yml

Speed up CI execution time by using default .NET Core SDK version pre-installed on hosted Github Runner
Reference: https://github.com/Energinet-DataHub/the-outlaws/issues/360

Remove DOTNET_VERSION

---

.github/workflows/cd.yml
.github/workflows/ci.yml

As a part of our new rollout strategy, we want to be able to always have an up to date `dotnet_latest` version besides the running version.
This is to support the possibility to find the latest release by the tag name `dotnet_latest`
This is an addition to the CD job, it will only create and maintain a new `dotnet_latest` release.
BE AWARE that we will do another iteration splitting infrastructure away from the dotnet package, so this is only to introduce a non breaking rollout

added create-latest-release to cd

---

build/infrastructure/env/t-001/mssqldb-this_override.tf

Set DB max size to 10 in T001 to comply with T Tier policy

Set DB max size to 10 to comply with Tier policy
